name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.7

      - name: Check out code
        uses: actions/checkout@v1

      - name: Test
        env:
          GO111MODULE: on
        run: make test
