name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          version: 1.12.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        path: ${{ go.module-path }}

      - name: Test
        working-directory: ${{ go.module-path }}
        env:
          GO111MODULE: on
        run: make test
